enabled: true

# Service
mongodb:
    enabled: false
redis:
    enabled: true
consul:
    enabled: false

console:
    enabled: true

console-api:
    enabled: true

identity:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/identity
      version: 1.6.7
    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30101
          protocol: TCP

secret:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/secret
      version: 1.6.7
    application:
        CONNECTORS:
            AWSSecretManagerConnector:
                aws_access_key_id: ___CHANGE_YOUR_ACCESS_KEY_ID___
                aws_secret_access_key: __CHANGE_YOUR_SECRET_ACCESS_KEY__
                region_name: __AWS_REGION_NAME__
    volumeMounts:
        application: []
        application_scheduler: []
        application_worker: []

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30102
          protocol: TCP


repository:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/repository
      version: 1.6.7
    application:
        ROOT_TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        ROOT_TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30103
          protocol: TCP


plugin:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/plugin
      version: 1.6.7
 
    scheduler: true
    worker: true
    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30104
          protocol: TCP


config:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/config
      version: 1.6.7

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30105
          protocol: TCP


inventory:
    enabled: true
    replicas: 1
    replicas_worker: 20
    image:
      name: public.ecr.aws/megazone/spaceone/inventory
      version: 1.6.7
    scheduler: true
    worker: true
    application:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
        collect_queue: collector_q

    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN
    application_worker:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#
    volumeMounts:
        application: []
        application_scheduler: []
        application_worker: []

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30106
          protocol: TCP


#    service:
#      type: LoadBalancer
#      annotations:
#          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#          external-dns.alpha.kubernetes.io/hostname: inventory.spaceone.dev
#      ports:
#        - name: grpc
#          port: 50051
#          targetPort: 50051
#          protocol: TCP
#


monitoring:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/monitoring
      version: 1.6.7

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30107
          protocol: TCP


statistics:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/statistics
      version: 1.6.7
 
    scheduler: true
    worker: true
    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30108
          protocol: TCP


billing:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/billing
      version: 1.6.7

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30109
          protocol: TCP


power-scheduler:
    enabled: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/power-scheduler
      version: 1.6.7
 
    scheduler: true
    worker: true
    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul
#            uri: debug/supervisor/TOKEN

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30110
          protocol: TCP

cost-saving:
    enabled: true
    scheduler: true
    worker: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/cost-saving
      version: 1.6.7

    application:
        CONNECTORS:
            ProductConnector:
                token: ___CHANGE_INVENTORY_MARKETPLACE_TOKEN___
                endpoint:
                    v1: grpc://inventory.portal.dev.spaceone.dev:50051


    application_scheduler:
        SCHEDULERS:
            cost_saving_scheduler:
                backend: spaceone.cost_saving.scheduler.cost_saving_scheduler.CostSavingScheduler
                queue: cost_saving_q
                interval: 3600
            CONNECTORS:
                ProductConnector:
                    token: ___CHANGE_INVENTORY_MARKETPLACE_TOKEN___
                    endpoint:
                        v1: grpc://inventory.portal.dev.spaceone.dev:50051

            TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 

    application_worker:
        CONNECTORS:
            ProductConnector:
                token: ___CHANGE_INVENTORY_MARKETPLACE_TOKEN___
                endpoint:
                    v1: grpc://inventory.portal.dev.spaceone.dev:50051

    volumeMounts:
        application: []
        application_worker: []
        application_scheduler: []
        application_rest: []

    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30111
          protocol: TCP


spot-automation:
    enabled: true
    scheduler: true
    worker: true
    rest: true
    replicas: 1
    image:
      name: public.ecr.aws/megazone/spaceone/spot-automation
      version: 1.6.7

# Overwrite application config
    application:
        CONNECTORS:
            ProductConnector:
                endpoint:
                    v1: grpc://inventory.portal.dev.spaceone.dev:50051 
                token: ___CHANGE_INVENTORY_MARKETPLACE_TOKEN___
        INTERRUPT:
            salt: ___CHANGE_SALT___
            endpoint: http://spot-automation-proxy.dev.spaceone.dev
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___

    # Overwrite scheduler config
    #application_scheduler: {}
    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___

    # Overwrite worker config
    #application_worker: {}
    application_worker:
        QUEUES:
            spot_controller_q:
                backend: spaceone.core.queue.redis_queue.RedisQueue
                host: redis
                port: 6379
                channel: spot_controller
        CONNECTORS:
            ProductConnector:
                endpoint:
                    v1: grpc://inventory.portal.dev.spaceone.dev:50051 
                token: ___CHANGE_INVENTORY_MARKETPLACE_TOKEN___
        INTERRUPT:
            salt: ___CHANGE_SALT___
            endpoint: http://spot-automation-proxy.dev.spaceone.dev


    service:
      type: NodePort
      ports:
        - name: grpc
          port: 50051
          targetPort: 50051
          nodePort: 30112
          protocol: TCP


marketplace-assets:
    enabled: false


# include config/alb.yaml (for ALB)
# include config/nlb.yaml (for NLB)
supervisor:
    enabled: true
    image:
      name: public.ecr.aws/megazone/spaceone/supervisor
      version: 1.6.7
    application: {}
    application_scheduler:
        TOKEN: ___CHANGE_YOUR_ROOT_TOKEN___ 
        NAME: root
        HOSTNAME: root-supervisor.svc.cluster.local
        BACKEND: KubernetesConnector
        CONNECTORS:
            RepositoryConnector:
                endpoint:
                    v1: grpc://repository.spaceone.svc.cluster.local:50051
            PluginConnector:
                endpoint:
                    v1: grpc://plugin.spaceone.svc.cluster.local:50051
            KubernetesConnector:
                namespace: root-supervisor
                start_port: 50051
                end_port: 50052
                headless: true
                replica:
                    inventory.Collector: 2
                    inventory.Collector?aws-ec2: 10
                    inventory.Collector?aws-cloud-services: 10
                    inventory.Collector?aws-power-state: 10
                    monitoring.DataSource: 2

#        TOKEN_INFO:
#            protocol: consul
#            config:
#                host: consul.spaceone.svc.cluster.local
#            uri: debug/supervisor/TOKEN

ingress:
    enabled: false

spaceone-initializer:
    enabled: false
    image:
        version: 1.6.2

domain-initialzer:
    enabled: false

#######################################
# TYPE 1. global variable (for docdb) 
#######################################
global:
    namespace: spaceone
    supervisor_namespace: root-supervisor
    backend:
        sidecar: []
        volumes: []
    frontend:
        sidecar: []
        volumes: []


#######################################
# TYPE 2. global variable (for mongodb cluster)
#######################################
#global:
#    namespace: spaceone
#    supervisor_namespace: root-supervisor
#    backend:
#        sidecar:
#            - name: mongos
#              image: mongo:4.4.0-bionic
#              command: [ 'mongos', '--config', '/mnt/mongos.yml', '--bind_ip_all' ]
#              volumeMounts:
#                - name: mongos-conf
#                  mountPath: /mnt/mongos.yml
#                  subPath: mongos.yml
#                  readOnly: true
#                - name: mongo-shard-key
#                  mountPath: /opt/mongos/mongo-shard.pem
#                  subPath: mongo-shard.pem
#                  readOnly: true
#        volumes:
#            - name: mongo-shard-key
#              secret:
#                  defaultMode: 0400
#                  secretName: mongo-shard-key
#            - name: mongos-conf
#              configMap:
#                  name: mongos-conf
