#console:
#  production_json:
#    CONSOLE_API:
#      ENDPOINT: https://console.api.example.com        # Change the endpoint
#    CONSOLE_API_V2:
#      ENDPOINT: https://console-v2.api.example.com     # Change the endpoint

#global:
#  shared_conf:
#    TOKEN: '{TOKEN}'                                   # Change the system token

identity:
  replicas: 4                                           # Change replica count of grpc pod

inventory:
  replicas: 4                                           # Change replica count of grpc pod
  replicas_worker: 4                                    # Change replica count of worker pod

# Change replica count for all the microservices