identity:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: identity
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 0
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

secret:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: secret
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 4
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

repository:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: repository
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 3
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

plugin:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: plugin
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 2
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

config:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: config
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 0
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

inventory:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: inventory
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 1
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

monitoring:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: monitoring
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 5
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10



statistics:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: statistics
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 5
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

billing:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: billing
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 5
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

notification:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: notification
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 5
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10


power-scheduler:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: power-scheduler
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 12
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

cost-saving:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: cost-saving
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 13
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

spot-automation:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: spot-automation
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 14
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

cost-analysis:
    database:
        DATABASES:
            default:
              username: ___CHANGE_YOUR_DB_USERNAME___
              password: ___CHANGE_YOUR_DB_PASSWORD___
              db: cost-analysis
              host: ___CHANGE_YOUR_DOCDB_CLUSTER_HOSTNAME___
              port: 27017
              ssl: False
              read_preference: PRIMARY
              maxPoolSize: 200
        CACHES:
            default:
              backend: spaceone.core.cache.redis_cache.RedisCache
              host: redis
              port: 6379
              db: 15
              encoding: utf-8
              socket_timeout: 10
              socket_connect_timeout: 10

